Document: legacy-widgets-for-gtk
Title: Debian legacy-widgets-for-gtk Manual
Author: <insert document author here>
Abstract: This manual describes what legacy-widgets-for-gtk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/legacy-widgets-for-gtk/legacy-widgets-for-gtk.sgml.gz

Format: postscript
Files: /usr/share/doc/legacy-widgets-for-gtk/legacy-widgets-for-gtk.ps.gz

Format: text
Files: /usr/share/doc/legacy-widgets-for-gtk/legacy-widgets-for-gtk.text.gz

Format: HTML
Index: /usr/share/doc/legacy-widgets-for-gtk/html/index.html
Files: /usr/share/doc/legacy-widgets-for-gtk/html/*.html
